// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHPCP_flhO9AX4qX-q96FjNkAdT1YMIRA',
    appId: '1:76601109599:web:5b38c95d84e2a0e355ffea',
    messagingSenderId: '76601109599',
    projectId: 'leads-tracker-app-1e6be',
    authDomain: 'leads-tracker-app-1e6be.firebaseapp.com',
    databaseURL: 'https://leads-tracker-app-1e6be-default-rtdb.firebaseio.com',
    storageBucket: 'leads-tracker-app-1e6be.firebasestorage.app',
    measurementId: 'G-Z1ZPQZBQSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZmzKdSNMKX6E4Pp2Fh6R7xxliaAiOz6E',
    appId: '1:76601109599:android:011f2a8d941e821255ffea',
    messagingSenderId: '76601109599',
    projectId: 'leads-tracker-app-1e6be',
    databaseURL: 'https://leads-tracker-app-1e6be-default-rtdb.firebaseio.com',
    storageBucket: 'leads-tracker-app-1e6be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtkK7xt-owR0XFvMfCWc-u8GZYXH0FGIo',
    appId: '1:76601109599:ios:ead3b58b37398fde55ffea',
    messagingSenderId: '76601109599',
    projectId: 'leads-tracker-app-1e6be',
    databaseURL: 'https://leads-tracker-app-1e6be-default-rtdb.firebaseio.com',
    storageBucket: 'leads-tracker-app-1e6be.firebasestorage.app',
    iosBundleId: 'com.example.trackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtkK7xt-owR0XFvMfCWc-u8GZYXH0FGIo',
    appId: '1:76601109599:ios:ead3b58b37398fde55ffea',
    messagingSenderId: '76601109599',
    projectId: 'leads-tracker-app-1e6be',
    databaseURL: 'https://leads-tracker-app-1e6be-default-rtdb.firebaseio.com',
    storageBucket: 'leads-tracker-app-1e6be.firebasestorage.app',
    iosBundleId: 'com.example.trackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHPCP_flhO9AX4qX-q96FjNkAdT1YMIRA',
    appId: '1:76601109599:web:dc1f913c6a5ec52d55ffea',
    messagingSenderId: '76601109599',
    projectId: 'leads-tracker-app-1e6be',
    authDomain: 'leads-tracker-app-1e6be.firebaseapp.com',
    databaseURL: 'https://leads-tracker-app-1e6be-default-rtdb.firebaseio.com',
    storageBucket: 'leads-tracker-app-1e6be.firebasestorage.app',
    measurementId: 'G-65PQWSN9WW',
  );
}
